/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing */

#ifndef _Included_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing
#define _Included_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing
 * Method:    setCallback
 */
JNIEXPORT void JNICALL Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setCallback
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setVideoCaptureByteBuffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setAudioRecordByteBuffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setAudioPlayByteBuffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL
Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setBeforeAudioMixByteBuffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setAudioMixByteBuffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL
Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_setVideoDecodeByteBUffer(JNIEnv *,
                                                                             jobject,
                                                                             jint,
                                                                             jobject);

JNIEXPORT void JNICALL
Java_net_lang_streamer_rtc_io_agora_ex_MediaPreProcessing_releasePoint(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
